#!/bin/bash

source config.txt

if [ -d $DST ]; then
	file="$DST/.files"
	if [ -f $file ] ; then
		rm $file
	fi
else
	mkdir $DST
	touch $DST/.gitkeep
fi

BASE_URL=${1:-\/}

echo $(date +"%T") "- Generating site"
./ssg5/ssg5 $SRC $DST "$SITE_NAME" "$BASE_URL" | sed 's/^/  /'
echo "---"