#!/bin/bash

source config.txt

if [ -d $DST ]; then
	file="$DST/.files"
	if [ -f $file ] ; then
		rm $file
	fi
else
	mkdir $DST
	touch $DST/.gitkeep
fi

echo "Generating site"
./ssg5/ssg5 $SRC $DST "$SITE_NAME" $1
echo "---"