#!/bin/bash

watch() {
	chsum1=""

	while [[ true ]]
	do
			chsum2=`find src/ -type f -exec md5 {} \;`
			if [[ $chsum1 != $chsum2 ]] ; then
					chsum1=$chsum2
					./generate /
			fi
			sleep .2
	done
}
watch